name: hk_explorer
description: HK Explorer - Gamified tourism in Hong Kong
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.16.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  image_picker: ^1.0.7
  http: ^1.2.0
  provider: ^6.1.1
  cached_network_image: ^3.3.1
  flutter_animate: ^4.3.0
  shimmer: ^3.0.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  confetti: ^0.7.0
  fl_chart: ^0.65.0
  timeago: ^3.6.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
